#!/usr/bin/env ruby
default_platform(:ios)

Dir[File.expand_path('helper/*.rb',__dir__)].each { |f| require_relative f }
Dir[File.expand_path('Fastfiles/*.rb',__dir__)].each { |f| import f }


lane :hello do

end
